name: Mirror public issues

on:
  issues:
    types: [opened, edited, labeled, unlabeled, reopened, closed]
  issue_comment:
    types: [created]

permissions:
  contents: read
  issues: write

env:
  PUBLIC_OWNER: santiago-larrain
  PUBLIC_REPO:  public-iee3112-proyecto-sec
  MIRROR_LABEL: public
  COPY_COMMENTS: true

jobs:
  # -------------------- SYNC DE ISSUES (título/cuerpo/estado) --------------------
  mirror_issue:
    if: ${{ github.event_name == 'issues' }}
    runs-on: ubuntu-latest
    steps:
      - name: Gate - issue tiene la etiqueta requerida (privado)
        id: gate
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const labels = (context.payload.issue?.labels || []).map(l => typeof l === 'string' ? l : l.name);
            core.setOutput('allowed', labels.includes(process.env.MIRROR_LABEL) ? 'true' : 'false');

      - name: Stop if not labeled
        if: ${{ steps.gate.outputs.allowed != 'true' }}
        run: echo "Issue without '${{ env.MIRROR_LABEL }}' label. Skipping."

      - name: Preflight public repo access (usa MIRROR_TOKEN)
        if: ${{ steps.gate.outputs.allowed == 'true' }}
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.MIRROR_TOKEN }}
          script: |
            const { data } = await github.rest.repos.get({ owner: process.env.PUBLIC_OWNER, repo: process.env.PUBLIC_REPO });
            if (!data.has_issues) core.setFailed('Issues are disabled in target public repo.');

      - name: Build payload & find mapping (privado)
        id: prep
        if: ${{ steps.gate.outputs.allowed == 'true' }}
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const src = context.payload.issue;
            const num = src.number;

            function sanitize(text) {
              if (!text) return '';
              let t = text;
              const danger = /(token|secret|password|apikey|PRIVATE KEY|authorization|bearer)/i;
              t = t.split('\n').filter(line => !danger.test(line)).join('\n');
              return t.trim();
            }

            const header = `> 🔗 Source: ${context.repo.owner}/${context.repo.repo}#${num}`;
            const bodySafe = sanitize(src.body || '');
            const mirroredBody = `${header}\n\n${bodySafe}\n\n<!-- MIRROR-SOURCE:${context.repo.owner}/${context.repo.repo}#${num} -->`;

            // Buscar mapping (comentario con marcador) en la PRIVADA
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: num,
              per_page: 100
            });
            const marker = /<!--\s*MIRROR-TARGET:\s*([^\s#\/]+)\/([^\s#]+)#(\d+)\s*-->/;
            let pubNumber = '';
            for (const c of comments) {
              const m = c.body && c.body.match(marker);
              if (m) { pubNumber = String(m[3]); break; }
            }

            core.setOutput('title', src.title);
            core.setOutput('body',  mirroredBody);
            core.setOutput('src_number', String(num));
            core.setOutput('pub_number', pubNumber);

      - name: Create public issue (first time)  # usa MIRROR_TOKEN
        id: create_public
        if: ${{ steps.prep.outputs.pub_number == '' }}
        uses: actions/github-script@v7
        env:
          TITLE: ${{ steps.prep.outputs.title }}
          BODY:  ${{ steps.prep.outputs.body }}
        with:
          github-token: ${{ secrets.MIRROR_TOKEN }}
          script: |
            const { data: created } = await github.rest.issues.create({
              owner: process.env.PUBLIC_OWNER,
              repo:  process.env.PUBLIC_REPO,
              title: process.env.TITLE,
              body:  process.env.BODY,
              labels: ['from-private']
            });
            core.setOutput('pub_number', String(created.number));

      - name: Write mapping marker in private issue  # usa GITHUB_TOKEN
        if: ${{ steps.prep.outputs.pub_number == '' && steps.create_public.outputs.pub_number != '' }}
        uses: actions/github-script@v7
        env:
          SRC_NUMBER: ${{ steps.prep.outputs.src_number }}
          PUB_NUMBER: ${{ steps.create_public.outputs.pub_number }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const srcNum = Number(process.env.SRC_NUMBER);
            const pubNum = Number(process.env.PUB_NUMBER);
            const marker = `<!-- MIRROR-TARGET:${process.env.PUBLIC_OWNER}/${process.env.PUBLIC_REPO}#${pubNum} -->`;
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: srcNum,
              body: `Mirrored to ${process.env.PUBLIC_OWNER}/${process.env.PUBLIC_REPO}#${pubNum}\n\n${marker}`
            });

      - name: Pick public issue number
        id: pick
        run: echo "PUB_NUM=${PUB_NUM}" >> $GITHUB_ENV
        env:
          PUB_NUM: ${{ steps.prep.outputs.pub_number != '' && steps.prep.outputs.pub_number || steps.create_public.outputs.pub_number }}

      - name: Sync title/body to public  # usa MIRROR_TOKEN
        if: ${{ env.PUB_NUM != '' }}
        uses: actions/github-script@v7
        env:
          PUB_NUM: ${{ env.PUB_NUM }}
          TITLE:   ${{ steps.prep.outputs.title }}
          BODY:    ${{ steps.prep.outputs.body }}
        with:
          github-token: ${{ secrets.MIRROR_TOKEN }}
          script: |
            await github.rest.issues.update({
              owner: process.env.PUBLIC_OWNER,
              repo:  process.env.PUBLIC_REPO,
              issue_number: Number(process.env.PUB_NUM),
              title: process.env.TITLE,
              body:  process.env.BODY
            });

      - name: Sync state (open/closed) to public  # usa MIRROR_TOKEN
        if: ${{ env.PUB_NUM != '' && (github.event.action == 'closed' || github.event.action == 'reopened') }}
        uses: actions/github-script@v7
        env:
          PUB_NUM: ${{ env.PUB_NUM }}
        with:
          github-token: ${{ secrets.MIRROR_TOKEN }}
          script: |
            await github.rest.issues.update({
              owner: process.env.PUBLIC_OWNER,
              repo:  process.env.PUBLIC_REPO,
              issue_number: Number(process.env.PUB_NUM),
              state: (context.payload.action === 'closed') ? 'closed' : 'open'
            });

  # -------------------- SYNC DE COMENTARIOS (privado -> público) --------------------
  mirror_comment:
    if: ${{ github.event_name == 'issue_comment' }}  # <- sin 'env' aquí
    runs-on: ubuntu-latest
    steps:
      - name: Skip whole job if COPY_COMMENTS is false
        id: copygate
        run: |
          if [ "${COPY_COMMENTS}" != "true" ]; then
            echo "COPY_COMMENTS is false; exiting."
            exit 78
          fi

      - name: Gate: issue tiene la etiqueta requerida (privado)
        id: gatec
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const labels = (context.payload.issue?.labels || []).map(l => typeof l === 'string' ? l : l.name);
            core.setOutput('allowed', labels.includes(process.env.MIRROR_LABEL) ? 'true' : 'false');

      - name: Stop if not labeled
        if: ${{ steps.gatec.outputs.allowed != 'true' }}
        run: echo "Issue without '${{ env.MIRROR_LABEL }}' label. Skipping comment."

      - name: Find mapping in private issue
        id: findmapc
        if: ${{ steps.gatec.outputs.allowed == 'true' }}
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const num = context.payload.issue.number;
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: num,
              per_page: 100
            });
            const marker = /<!--\s*MIRROR-TARGET:\s*([^\s#\/]+)\/([^\s#]+)#(\d+)\s*-->/;
            let pubNumber = '';
            for (const c of comments) {
              const m = c.body && c.body.match(marker);
              if (m) { pubNumber = String(m[3]); break; }
            }
            core.setOutput('pub_number', pubNumber);

      - name: Skip if no mapping
        if: ${{ steps.findmapc.outputs.pub_number == '' }}
        run: echo "No mapping. Skipping."

      - name: Mirror new comment to public  # usa MIRROR_TOKEN
        if: ${{ steps.findmapc.outputs.pub_number != '' && github.event.comment.user.type != 'Bot' }}
        uses: actions/github-script@v7
        env:
          PUB_NUM: ${{ steps.findmapc.outputs.pub_number }}
        with:
          github-token: ${{ secrets.MIRROR_TOKEN }}
          script: |
            function sanitize(t){
              if(!t) return '';
              return t.split('\n').filter(l=>!/(token|secret|password|apikey|PRIVATE KEY|authorization|bearer)/i.test(l)).join('\n').trim();
            }
            const body = sanitize(context.payload.comment.body || '');
            if (!body) return;
            await github.rest.issues.createComment({
              owner: process.env.PUBLIC_OWNER,
              repo:  process.env.PUBLIC_REPO,
              issue_number: Number(process.env.PUB_NUM),
              body
            });
